chat/urls.py
from django.contrib import admin
from django.urls import path
from .views import room, chat_list, create_group

app_name = 'chat'

urlpatterns = [
    path('room/<str:room_name>/', room, name='room'),
    path('list/', chat_list, name='chat_list'),
    path('create_group/', create_group, name='create_group'),
]

websocial/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view

from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(),name="home"),
    path('', include('accounts.urls')),
    path('', include('chat.urls')),
    path('login/',auth_view.LoginView.as_view(template_name='accounts/login.html',redirect_authenticated_user=True),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

try:
    if settings.DEBUG:
        # Django Debug Toolbar
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
except:
    pass

chat/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class PublicRoom(models.Model):
	title = models.CharField(max_length=256)
	users = models.ManyToManyField(User,blank=True)
	last_active_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title


class PublicMessage(models.Model):
	content = models.CharField(max_length=256,blank=False)
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	seen_by = models.ManyToManyField(User,related_name="seen_by_users")
	room = models.ForeignKey(PublicRoom,related_name="public_room",on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "%s - %s"%(self.user,self.room)

class PrivateRoom(models.Model):
	title = models.CharField(max_length=256)
	user_one = models.ForeignKey(User,blank=True,on_delete=models.CASCADE,related_name='user_one')
	user_two = models.ForeignKey(User,blank=True,on_delete=models.CASCADE,related_name='user_two')
	last_active_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "%s - %s"%(self.user_one,self.user_two)

class PrivateMessage(models.Model):
	content = models.CharField(max_length=256,blank=False)
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	is_seen = models.BooleanField(default=False)
	room = models.ForeignKey(PrivateRoom,related_name="private_room",on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "%s - %s"%(self.user,self.room)

chat/forms.py
from django import forms
from .models import PublicRoom

class PublicRoomForm(forms.ModelForm):
    class Meta:
        model = PublicRoom
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['users'].required = True

chat/views.py
import json
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Max, Q, BooleanField, Value, Count
from itertools import chain

from .models import PrivateRoom, PublicRoom
from .forms import PublicRoomForm
# Create your views here.


def room(request, room_name):
    room = PrivateRoom.objects.filter(user_one=request.user,user_two=room_name)
    users = User.objects.all().exclude(id=request.user.id)

    if room.count() == 0:
        room = PrivateRoom.objects.filter(user_one=room_name,user_two=request.user)
        if room.count() == 0:
            user = User.objects.get(id=room_name)
            room = PrivateRoom.objects.create(title=str(request.user.id)+room_name,user_one=user,user_two=request.user)
        else:
            room = room.first()
    else:
        room = room.first()

    room_name=room.title
    return render(request, 'chat/chat_room_advanced.html', {
        'room_name': room_name,
        'users': users
    })


@login_required(login_url='/login')
def chat_list(request):
    users = User.objects.all().exclude(id=request.user.id)
    groups = PublicRoom.objects.filter(users=request.user.id).annotate(is_group=Value(True,output_field=BooleanField()))
    private_chats = PrivateRoom.objects.filter(Q(user_one=request.user.id)|Q(user_two=request.user.id)).annotate(is_group=Value(False,output_field=BooleanField()),message_count=Count('private_room')).filter(message_count__gt=0)
    chat_list = sorted(chain(groups, private_chats),key=lambda instance: instance.last_active_at, reverse=True)

    return render(request, 'chat/chat_room_advanced.html', {
        'chat_list': chat_list
    })

def create_group(request):

    if request.method == "POST":
        form = PublicRoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("chat:chat_list")
        else:
            form = form
    else:
        form = PublicRoomForm()

    return render(request,"chat/create_group.html",{"form":form})
    # return HttpResponse({"form":form})

chat/templates/chat/chat_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Login{% endblock %}

{% block content %}
    <div>
        <a href="{% url 'logout' %}"><button class="btn btn-primary" type="button" name="button">Logout</button></a>
    </div>
    {% for user in users %}
        <div>
            <a href="{% url 'chat:room' room_name=user.id %}"><h4>{{user.first_name}} {{user.last_name}}</h4></a>
        </div>
    {% endfor %}
{% endblock %}

chat/templates/chat/chat_room.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Login{% endblock %}
{% block head %}

{% endblock %}

{% block content %}
  <div class="text-center">
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
  </div>

  <script>
    const roomName = JSON.parse(document.getElementById('room-name').textContent);
  
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );
  
    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        if ({{user.id}} == data.user){
            document.querySelector('#chat-log').value += (data.message + "sent" + '\n');
        }
        else{
            document.querySelector('#chat-log').value += (data.message + "received" +'\n');
        }
    };
  
    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };
  
    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };
  
    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'user': {{user.id}}
        }));
        messageInputDom.value = '';
    };
  </script>
{% endblock %}

chat/templates/chat/create_group.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Home{% endblock %}

{% block content %}
<form action="{% url 'chat:create_group' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="text-center">
        <input class="btn btn-outline-primary btn-sm" type="submit" name="submit" value="Submit">
        <a href="{% url 'chat:chat_list' %}"><button class="btn btn-outline-danger btn-sm" type="button" name="cancel">Cancel</button></a>
    </div>
</form>
{% endblock %}