accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import sign_up, search_user, get_users

app_name = 'accounts'

urlpatterns = [
    path('signup/', sign_up, name='signup'),
    path('search_user/', search_user, name='search_user'),
    path('get_user/', get_users, name='users'),
]

chat/urls.py
from django.contrib import admin
from django.urls import path
from .views import room, chat_list, create_group

app_name = 'chat'

urlpatterns = [
    path('room/<str:room_name>/', room, name='room'),
    path('list/', chat_list, name='chat_list'),
    path('create_group/', create_group, name='create_group'),
]

websocial/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view

from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(),name="home"),
    path('', include('accounts.urls')),
    path('', include('chat.urls')),
    path('login/',auth_view.LoginView.as_view(template_name='accounts/login.html',redirect_authenticated_user=True),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

try:
    if settings.DEBUG:
        # Django Debug Toolbar
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
except:
    pass

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block head %}{% endblock %}
</head>
<body>
    <!-- <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
    </nav> -->
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">WebSocial</a>
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chat:create_group' %}">Create Group</a>
            </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav ml-auto">
            <span class="navbar-text">
                {{request.user.first_name}} {{request.user.last_name}}
              </span>
			{% if request.user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'logout' %}">Logout</a>
				</li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
			{% endif %}
        </ul>
      
    </nav>

    <div class="container">
        <div class="">
          {% block content %}
  
          {% endblock %}
        </div>
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Welcome to WebSocial</h1>
<a href="{% url 'login' %}"><button class="btn btn-primary" type="button" name="button">Login</button></a>
<a href="{% url 'accounts:signup' %}"><button class="btn btn-primary" type="button" name="button">SignUp</button></a>
{% endblock %}